apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: extraction
  labels:
    app.kubernetes.io/name: backend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: backend
  ports:
    - name: http
      port: 3001
      targetPort: http
      protocol: TCP
